### ISSUE TITLE
Retrieve Available Skills

### ISSUE THREAD

**Issue by jminuscula** [LivePersonInc/node-agent-sdk#50]
Hi,

I'm trying to get my bot query the available skills before transferring a conversation. It looks like there is an endpoint on the Chat Agent API to do this [1], but since bot conversations are on Messaging, there is no `chatId` to perform the query with.

What's the preferred way to get this information?

Thanks!

[1] https://developers.liveperson.com/agent-chat-agent-retrieve-skills.html

**Comment by donmanguno** [comment]
Hi @jminuscula, there is currently no comparable API method for messaging.  The concept of skill availability in asynchronous messaging environment is quite different from that of traditional chat, so we are working on a new method for the [Messaging Operations API](https://developers.liveperson.com/data-messaging-operations-overview.html) that will return skill utilization information. I can't provide an ETA, but the new methods should be added to the documentation soon.

**Comment by donmanguno** [comment]
HI @jminuscula, the new methods have been published: https://developers.liveperson.com/data-messaging-operations-messaging-current-queue-health.html

In addition, we'll be releasing a new API for calculating estimated wait time of the target skill soon.

**Comment by jminuscula** [comment]
Thanks @donmanguno!
